CREATE TABLE IF NOT EXISTS mainMenuEntry

CREATE TABLE IF NOT EXISTS template

CREATE TABLE IF NOT EXISTS gallery

CREATE TABLE IF NOT EXISTS imgvid

CREATE TABLE IF NOT EXISTS subMenuEntry

CREATE TABLE IF NOT EXISTS entry

CREATE TABLE IF NOT EXISTS galleryEntry

